name: Build mod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full commit history

      - name: Make gradlew executable  # NEW STEP ADDED HERE
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Find build artifact
        id: find_jar
        run: |
          JAR_PATH=$(find ./build/libs -name '*.jar' ! -name '*sources*' ! -name '*dev*' -print -quit)
          echo "jar_path=${JAR_PATH}" >> $GITHUB_OUTPUT
          echo "Found JAR: ${JAR_PATH}"

      - name: Prepare commit info
        id: commit_info
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          COMMIT_MSG=$(git log -1 --pretty=%B | head -n1)
          COMMIT_DATE=$(git log -1 --format=%cd --date=short)
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "commit_msg=${COMMIT_MSG}" >> $GITHUB_OUTPUT
          echo "commit_date=${COMMIT_DATE}" >> $GITHUB_OUTPUT

      - name: Rename artifact with commit info
        run: |
          NEW_NAME="mod-${{ steps.commit_info.outputs.short_sha }}.jar"
          mv "${{ steps.find_jar.outputs.jar_path }}" "./build/libs/${NEW_NAME}"
          echo "new_jar_path=./build/libs/${NEW_NAME}" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mod-build
          path: ${{ steps.rename.outputs.new_jar_path }}

      - name: Create nightly.link URL
        id: nightly_link
        run: |
          ARTIFACT_URL="https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/mod-build.zip"
          echo "url=${ARTIFACT_URL}" >> $GITHUB_OUTPUT

      - name: Send Discord notification
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          args: |
            **New Mod Build Available!** 
            **Commit:** [${{ steps.commit_info.outputs.short_sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            **Message:** ${{ steps.commit_info.outputs.commit_msg }}
            **Date:** ${{ steps.commit_info.outputs.commit_date }}
            **Built by:** ${{ github.actor }}
            **Download:** [${{ steps.commit_info.outputs.short_sha }}.jar](${{ steps.nightly_link.outputs.url }})
            **Full Log:** https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
